### ISSUE TITLE
0x52 - Malicious user can permanently break VUSD#processWithdrawals by returning huge amounts of data

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-hubble-exchange-judging#158]
0x52

high

# Malicious user can permanently break VUSD#processWithdrawals by returning huge amounts of data

## Summary

VUSD#processWithdraw makes a call to withdrawal.usr to send the withdrawn gas token. It then stores the return data of the call in memory. A malicious user could set the withdrawal target to a malicious contract that would return an extremely large data amount that would guaranteed cause an OOG error when loaded to memory. The result is that all withdrawals would be permanently locked causing massive loss to all VUSD holders.

NOTE: I am submitting this as a separate issue apart from my other two similar issues. I believe it should be a separate issue because even though the outcome is similar the root cause is different. The vulnerability exploited in this issue is that the return data is stored and that there is no cap on it's size. Capping the gas usage of the call won't fix this.

## Vulnerability Detail

See summary.

## Impact

All withdrawals can be permanently broken

## Code Snippet

[VUSD.sol#L65-L85](https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/main/hubble-protocol/contracts/VUSD.sol#L65-L85)

## Tool used

Manual Review

## Recommendation

Cap the data returned or don't store the return data at all

Duplicate of #116

**Comment by djb15** [comment]
Escalate for 5 USDC

According the Sherlock duplication rules this should be a duplicate of #153. The core vulnerability in the code that makes both attack paths possible is that the withdrawals are executed in a loop over all the withdrawals in the queue. Although the information in this report is correct, just removing the queue mechanism solves both issues (the user would only be able to grief themselves now by returning large amounts of data).

If you look at some of the duplicates of #153 like #57 you'll see that there isn't a distinction between griefing and permanently breaking the withdrawal process. All these issues exist due to the same root cause.

Based on the sponsor comments in #153 it sounds like they aren't being encouraged to remove the queue mechanism but rather work around it. Like some of the duplicates have mentioned, you'd still be able to gas grief by queueing a large number of small withdrawals. I believe my recommendation in #57 is a more appropriate way to properly fix this family of issues.

**Comment by sherlock-admin2** [comment]
> Escalate for 5 USDC
> 
> According the Sherlock duplication rules this should be a duplicate of #153. The core vulnerability in the code that makes both attack paths possible is that the withdrawals are executed in a loop over all the withdrawals in the queue. Although the information in this report is correct, just removing the queue mechanism solves both issues (the user would only be able to grief themselves now by returning large amounts of data).
> 
> If you look at some of the duplicates of #153 like #57 you'll see that there isn't a distinction between griefing and permanently breaking the withdrawal process. All these issues exist due to the same root cause.
> 
> Based on the sponsor comments in #153 it sounds like they aren't being encouraged to remove the queue mechanism but rather work around it. Like some of the duplicates have mentioned, you'd still be able to gas grief by queueing a large number of small withdrawals. I believe my recommendation in #57 is a more appropriate way to properly fix this family of issues.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Agreed with escalation.

Based on the comment by lead judge in https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/153#issuecomment-1640824294 , #153 and #160 are grouped together (because it shows different ways of consuming all gas) and this is a separate issue but it is specifically mentioned in this issue that

> guaranteed cause an OOG error when loaded to memory

If this is a separate issue to #153 then we need to look at all the other issues that are marked duplicate as well.

In fact, my issue #116 (and @djb1 's #57 and a few others ) forces a **PERMANENT** DOS on the `processWithdrawal` function by consuming more than 30mil gas on a **SINGLE** external call i.e. the fix suggested by #153 (to add the nonreentrant modifer to mintWithReserve withdraw and withdrawTo) does not fix our vulnerability.

#153 and some of its dups should be a medium instead of a high considering the effort and capital requirements needed and how the DOS is only a temporary DOS and not a permanent like ours.

**Comment by ctf-sec** [comment]
the root cause is not about execute the code in a withdrawal queue

capping the gas limit in external call does not fix this issue

the root cause is the returned data is emitted in the event

so the root cause is distinct enough to be a separate issue

the severity is clearly high because in the withdrawal loop, one malicious contract that consume a lot of gas clearly impact other user's withdrawal.

for all issue that outline how to waste gas in external call, they are grouped in #153 

Still think needs to be a separate issue

https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/1f9a5ed0ca8f6004bbb7b099ecbb8ae796557849/hubble-protocol/contracts/VUSD.sol#L79C17-L79C80

```solidity
emit WithdrawalFailed(withdrawal.usr, withdrawal.amount, data);
```

Same finding in the past contest my friend o(╥﹏╥)o

https://github.com/sherlock-audit/2023-02-gmx-judging/issues/141

**Comment by djb15** [comment]
Hey thanks for the input. Just to be clear I'm not saying the root cause is about "executing code in the withdrawal queue", I'm saying the root cause is "having the withdrawal queue".

The withdrawal queue isn't doing anything useful like escrowing funds so it should be removed imo. None of these issues would exist if the withdrawal queue was removed and a 1 step withdrawal was used instead. I don't really understand why the sponsor isn't being encouraged to remove the queue tbh, keen to understand why not.

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #116 
More context 
https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/116#issuecomment-1666049537

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [djb15](https://github.com/sherlock-audit/2023-04-hubble-exchange-judging/issues/158/#issuecomment-1642250276): accepted

**Comment by IAm0x52** [comment]
Fix looks good. Return data is no longer stored preventing this DOS
